"""All reusable product copy in one place; English is the initial UI locale."""

PROFILES = ["Coding", "Research / Reading", "Office / Writing", "Creative", "Mixed"]
CATEGORIES = ["IDE", "Browser", "Reader", "Office", "Creative", "Communication", "Entertainment", "Other"]
LABELS = ["Focused", "Normal", "Distracted", "Rest", "Not sure"]

EN = {
    "app": "Focus Pet",
    "tagline": "A little company. Room for your own rhythm.",
    "welcome": "Meet your quiet desktop companion",
    "welcome_note": "An estimate of your work rhythm, with room for you to disagree.",
    "choose_character": "Choose your companion",
    "choose_profile": "A starting point for your rhythm",
    "profile_note": "Your profile is a changeable starting prior. It never creates training labels.",
    "privacy_intro": "Your activity stays on this computer",
    "privacy_text": "With your permission, Focus Pet counts keyboard, click, scroll and pointer activity; idle time; and broad foreground app categories. It never records typed text, passwords, clipboard, window titles, page contents, screenshots, audio or pointer paths. No account, uploads or telemetry. Local storage is not encrypted by this app.",
    "consent": "I agree to local activity collection. System permissions may be requested.",
    "start": "Start with local activity",
    "demo": "Try a synthetic demo",
    "demo_note": "Demo data stays separate from your real history and personal models.",
    "status": "Your rhythm, right now",
    "dashboard": "Today & learning",
    "settings": "Settings",
    "focus": "Focus",
    "focus_note": "Estimated engagement · not output or prediction confidence",
    "workload": "Work Load",
    "workload_note": "Work rhythm index · not medical fatigue",
    "source": "Estimate source",
    "observed": "Observed activity",
    "coverage": "Signal coverage",
    "uncertainty": "Uncertainty (entropy)",
    "evidence": "What this estimate uses",
    "no_evidence": "Waiting for a valid activity window. Missing signals are not zero activity.",
    "stale": "Held during a data gap",
    "correct": "Correct a recent segment",
    "start_rest": "Take a 5 minute break",
    "end_rest": "Finish my break",
    "quiet": "Quiet for now",
    "snooze": "Remind me later",
    "restore": "Restore companion",
    "hide": "Hide companion",
    "pause": "Pause collection",
    "resume": "Resume collection",
    "quit": "Quit Focus Pet",
    "choose": "Choose companion…",
    "disable_through": "Turn off click-through",
    "through": "Full click-through",
    "through_note": "The menu-bar icon restores your companion and turns click-through off.",
    "through_unavailable": "Full click-through requires an available system tray. It remains off so your companion can always be recovered.",
    "reply": "One step at a time.",
    "timeline": "Today's timeline",
    "timeline_note": "Select a segment to correct it. Gaps mean evidence was unavailable.",
    "curves": "Focus & Work Load",
    "plot_legend": "● Focus (left, 0–100)      ● Work Load (right, continuous)      ⋯ Work Load reference: 100",
    "distribution": "Estimated state distribution",
    "feedback": "Your corrections",
    "learning": "Learning from your feedback",
    "learning_tab": "Learning",
    "feedback_note": "A long correction is still one independent feedback episode. Original predictions are preserved.",
    "learning_note": "Personal learning activates only after validation and new shadow evidence. Synthetic demonstrations do not validate long-term benefit.",
    "empty_history": "Your timeline will appear after the first valid estimate.",
    "empty_feedback": "No corrections yet. You decide when an estimate needs another perspective.",
    "missing_feedback": "At least 30 valid work episodes across 2 days and 3 sessions; 5 episodes for each work state. Validation and future shadow evidence are also required.",
    "train": "Train candidate",
    "calibrate": "Calibrate Work Load",
    "cancel_job": "Cancel current job",
    "rollback_model": "Revert personal model",
    "rollback_parameters": "Revert load parameters",
    "training_status": "Training / calibration",
    "correction_title": "How was that segment for you?",
    "correction_note": "Choose what best describes your experience, or Not sure. This is a correction, not a score.",
    "target": "Target segment",
    "recent": "Most recent",
    "before_segment": "Period ending at this segment",
    "minutes": "minutes",
    "save_feedback": "Save correction",
    "revise": "Revise correction",
    "withdraw": "Withdraw correction",
    "cancel": "Cancel",
    "save": "Save changes",
    "close": "Close",
    "general": "Companion",
    "privacy": "Privacy & data",
    "applications": "App categories",
    "reminders": "Reminders",
    "size": "Companion size",
    "always_on_top": "Keep companion above other windows",
    "quiet_hours": "Quiet hours (24 hour local time)",
    "quiet_hours_hint": "For example 22:00–08:00. Leave both fields empty to disable.",
    "reminder_frequency": "Minimum reminder spacing",
    "sound": "Play reminder sound (off by default)",
    "startup": "Launch at sign-in (off by default)",
    "startup_note": "Sign-in launch uses the platform adapter when supported.",
    "permissions": "Collection capabilities",
    "permissions_note": "Each capability is independent. Denied or unavailable input is missing evidence.",
    "grant": "Review / grant collection consent",
    "revoke": "Revoke consent & stop reading",
    "retention_buckets": "Keep aggregate buckets for",
    "retention_features": "Keep derived history for",
    "days": "days",
    "export": "Export my local data…",
    "delete": "Delete all local data…",
    "delete_title": "Delete local history and learned models",
    "delete_note": "This removes activity, features, feedback, model files and pending learning tasks for the current mode. Type DELETE to continue.",
    "export_title": "Export local history",
    "export_filter": "JSON files (*.json)",
    "mapping_note": "Only a local application identifier is used for category mapping. Browser never automatically means distracted, and IDE never guarantees focused.",
    "app_id": "Application identifier",
    "category": "Category",
    "add_mapping": "Save category mapping",
    "load_question": "Would a break help right now?",
    "load_note": "This separate feedback helps validate Work Load parameters. It is not a work-state label.",
    "yes": "Yes",
    "no": "No",
    "not_sure": "Not sure",
    "audit_question": "A small check-in, if you have a moment",
    "audit_note": "What describes the highlighted past segment? This check-in hides the prediction to avoid steering your answer.",
    "skip": "Skip this check-in",
    "local": "LOCAL ONLY",
    "demo_badge": "SYNTHETIC DEMO",
    "real_badge": "LOCAL ACTIVITY",
    "reset_cycle": "Start a new work cycle",
    "reset_note": "A new cycle sets Work Load to zero and records an explicit reset. Normal task changes do not reset it.",
    "restart_title": "Welcome back. There is a gap in the history.",
    "restart_note": "Work Load was held while the app could not observe activity. Continue with that value, or explicitly begin a new cycle. An overnight gap is never assumed to be a rest.",
    "continue_cycle": "Continue previous cycle",
    "confirm_recent_rest": "Confirm a recent rest",
    "confirm_recent_rest_note": "How many minutes immediately before returning were an intentional rest? Only the bounded interval you declare can restore Work Load.",
    "retention_feedback": "Keep feedback for",
    "retention_models": "Keep inactive model versions for",
    "no_data": "—",
    "version": "Model version",
    "parameter_version": "Load parameter version",
    "episodes": "Valid feedback episodes",
    "days_covered": "Days represented",
    "sessions": "Work sessions",
    "last_training": "Last training attempt",
    "validation": "Validation status",
    "missing": "Evidence still needed",
    "saved": "Saved locally.",
    "feedback_submitted": "Rest preference submitted",
    "load_feedback_saved": "Rest preference saved locally. Thank you.",
    "notice": "Focus Pet",
    "invalid_time": "Use valid 24-hour times such as 22:00 and 08:00.",
    "permission_required": "Collection remains stopped until you choose to grant consent.",
    "time": "Time",
    "state": "State",
    "duration": "Duration",
    "label": "Your label",
    "active": "Active",
    "withdrawn": "Withdrawn",
    "superseded": "Revised",
    "delete_range": "Delete a date range…",
    "delete_range_title": "Delete local history in a time range",
    "delete_range_note": "Enter local start and end as YYYY-MM-DD HH:MM, separated by / . Related feedback and learned versions are invalidated. This cannot be undone.",
    "invalid_range": "Enter a valid start before the end, for example 2026-09-01 09:00 / 2026-09-01 12:00.",
    "period": "Period",
    "status_col": "Status",
    "details": "Details",
    "generic-prior": "Generic rule prior",
    "personal-model": "Personal model",
    "user-declaration": "Your declaration",
    "data-insufficient": "Insufficient evidence",
}


def tr(key: str) -> str:
    return EN.get(key, key)
